### ISSUE TITLE
Add merchant and item description 

### ISSUE THREAD

**Issue by CypherpunkDev** [CypherpunkPay/CypherpunkPay#5]
@khand100:

> Could you add an optional item description field like btcpayserver has? This would for example be shown during the checkout and especially on the last payment waiting screen, so customers are reassured for what they are currently paying. With btcoayserver I also used this to display the fiat price. Here is a mock with a simple `<h2 class="subtitle">item description</h2>` under the title.

**Comment by CypherpunkDev** [comment]
As a first step I just added default description to indicate original fiat amount and the donation-vs-merchant payment type. More customization will follow.

**Comment by CypherpunkDev** [comment]
Done via optional `beneficiary` and `what_for` parameters to HTML form. This works for both merchants and donations.

**Comment by khand100** [comment]
Thanks for implementing it. But I think it is too opinionated, especially for the donations without beneficiary and what_for.
What if I want to donate for an evil cause 😄 I think just "Donation of $1" would be better.

Also for both cases a path with only "what_for" is missing. Here is my proposal, where the only "what_for" case gives the most flexibility. Although even the prefixed "for" in that cases limits the possibilities.

````jinja2
<h2 class="subtitle is-6 has-text-link-dark" style="margin-top: -1em;">
    &raquo;
    {% if charge.is_donation() %}
        Donation of {{ view.formatted_currency_amount(charge.total, charge.currency) | safe }}
        {% if charge.beneficiary and charge.what_for %}
            to {{ charge.beneficiary }} for {{ charge.what_for }}
        {% endif %}
        {% if charge.beneficiary and not charge.what_for %}
            to {{ charge.beneficiary }}
        {% endif %}
        {% if not charge.beneficiary and charge.what_for %}
            for {{ charge.what_for }}
        {% endif %}
    {% else %}
        Payment of {{ view.formatted_currency_amount(charge.total, charge.currency) | safe }}
        {% if charge.beneficiary and charge.what_for %}
            to {{ charge.beneficiary }} for {{ charge.what_for }}
        {% endif %}
        {% if charge.beneficiary and not charge.what_for %}
            to {{ charge.beneficiary }} for order {{ charge.merchant_order_id }}
        {% endif %}
        {% if not charge.beneficiary and charge.what_for %}
            for {{ charge.what_for }}
        {% endif %}
    {% endif %}
</h2>
````

**Comment by CypherpunkDev** [comment]
Thanks! I pushed a commit allowing for more flexibility when only `what_for` is provided. The separate beneficiary and what_for fields may be a bit superfluous for donations but I wanted to have it consistent with merchant payments.

**Comment by khand100** [comment]
It's an improvement. But I actually care more about the payment branch of the template, even with your change it is still not possible to only send what_for. Nothing will get displayed (only the "Payment of" part), which was the first thing that happened when I tried it.  
Sorry if that was not clear, I should have used a diff. The donation was just an example.

**Comment by CypherpunkDev** [comment]
I mirrored the change to merchant payment branch as well. Providing only `what_for` gives the most flexibility.

**Comment by khand100** [comment]
Looks good, thanks.
